### ISSUE TITLE
May the `ext` option be regexp?

### ISSUE THREAD

**Issue by dickeylth** [soenkekluth/connect-ssi#6]
Currently the `ext` option only support string, may it support regexp? Thank you!

**Comment by nfriedly** [comment]
Do you really need a regex, or would a list work? (like `{ext: ['.shtml', '.html'] }` )

**Comment by dickeylth** [comment]
If regexp could be supported, that would do the best.
Otherwise a list would be acceptable, thank you!

**Comment by nfriedly** [comment]
A regexp is trickey because there isn't a straightforward way to determine which file to serve when the url ends in `/`. Usually we can just do `"index" + options.ext`, but that won't work with a regex.

A list could work there, but it'd be a bit of work that I don't think I can get to right away. However, for a quick workaround, you can just do multiple instances to basically get a list:

```js
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.shtml'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.html'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.htm'
}));
// etc...
```

That would handle .shtml, .html, and .htm - and in the case of a `/` url, it would look for the index file in that order.

**Comment by dickeylth** [comment]
OK, I'll try the quick workaround for the moment, thank you!

**Comment by 2dareis2do** [comment]
A list could work there, but it'd be a bit of work that I don't think I can get to right away. However, for a quick workaround, you can just do multiple instances to basically get a list:

app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.shtml'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.html'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.htm'
}));
// etc...


This is what I was wondering about. Need to support the types of files you describe. thanks.

**Comment by 2dareis2do** [comment]
Do you have to use next() for this to work?

**Comment by nfriedly** [comment]
Are you asking about [this use of next()](https://github.com/soenkekluth/connect-ssi/blob/master/lib/connect-ssi.js#L38)? That is necessary, otherwise other URLs (images, CSS, etc) wouldn't work.

**Comment by 2dareis2do** [comment]
Ok just trying to figure out how to serve multiple indexes as mentioned above but it only seems to parse first one. Where about s can I put a next function as this function only seems to accept object?

**Comment by nfriedly** [comment]
You shouldn't need to add the `next()` yourself, can you show me your code?

**Comment by 2dareis2do** [comment]
App.use(connectSSI({
  BaseDir: __relativeRootParh + __rootPath , ext: '.shtml'
}));

App.use(connectSSI({
  BaseDir: __relativeRootParh + __rootPath , ext: '.html'
}));

Thx

**Comment by nfriedly** [comment]
I just tested it with the following setup:

```
index.js
public/
  - index.shtml
  - index.html
  - index.htm
```

`index.js`:

```js
var express = require('express');
var app = express();
var connectSSI = require('connect-ssi');

app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.shtml'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.html'
}));
app.use(connectSSI({
    baseDir: __dirname + '/public',
    ext: '.htm'
}));

app.listen(2500);
console.log('listening at http://localhost:2500');
```

When I run that, it serves up `index.shtml`. If I delete that file, it serves up `index.html`. If I delete that one, it serves up `index.htm`. So it worked exactly as expected.

What behavior are you seeing / expecting?

**Comment by 2dareis2do** [comment]
which I put first runs. So if I put shrimp it runs but then for html index I get  error eminent no such file or directory open c:/windows file path/index.html

For example if I put .html first at error (native)

So I am looking to support both concurrently in different paths folders etc

**Comment by 2dareis2do** [comment]
Shrimp = .shtml

**Comment by 2dareis2do** [comment]
Eminent = ENOENT

**Comment by nfriedly** [comment]
That's strange..  Do you have anything else (such as `express.static()`) running before connectSSI? Can you post your complete code?

Also, BTW, you can edit comments from the desktop interface. And, the `<>` button will format code blocks.

**Comment by 2dareis2do** [comment]
Yes u do have static running before hand. Unfortunately I can't paste all my code.

**Comment by 2dareis2do** [comment]
I do rather

**Comment by 2dareis2do** [comment]
Ok figured it out. Index was adding a query string . Refreshing without query string Resolved issue and loads index as expected.

Thank for your quick responses and I will try to edit my messy trail when I get home this evening.

d:)

**Comment by nfriedly** [comment]
Ok, cool. I'm going to close this for now, then.
