### ISSUE TITLE
Most HTTP response headers are missing

### ISSUE THREAD

**Issue by LordPachelbel** [soenkekluth/connect-ssi#9]
I'm not sure if `connect-ssi` or `node-ssi` is doing this, but when I use `connect-ssi` my `.html` files are served with most of the usual response headers missing. For my immediate purposes I only need the `Content-Type` header preserved, but ideally all of the headers would be.

Request headers:
```
Host: localhost:4000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
```

Response headers when using only `grunt-contrib-connect`:

```
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Connection: keep-alive
Content-Length: 7816
Content-Type: text/html; charset=UTF-8
Date: Tue, 22 Nov 2016 23:13:39 GMT
Etag: W/"1e88-1588e50f401"
Last-Modified: Tue, 22 Nov 2016 23:13:39 GMT
```

Response headers when using `connect-ssi` as middleware for `grunt-contrib-connect`:

```
Connection: keep-alive
Content-Length: 8591
Date: Tue, 22 Nov 2016 23:25:13 GMT
```

My Grunt task:
```javascript
connect: {
  server: {
    options: {
      port: 4000,
      base: 'build',
      hostname: '*',
      middleware: function(connect, options, middlewares) {
        if (!Array.isArray(options.base)) {
          options.base = [options.base];
        }
        var directory = options.directory || options.base[options.base.length - 1];

        middlewares.unshift(connectSSI({
          baseDir: directory,
          ext: '.html'
        }));
        return middlewares;
      }
    }
  }
}
```

**Comment by LordPachelbel** [comment]
I didn't realize until now that there was a pull request (#8) that fixes this.

**Comment by nfriedly** [comment]
LOL, and I forgot/didn't realize that I had commit & publish rights. Should be live now as v1.1.1. It just adds a content-type header, but that's probably the most important one. Feel free to send another PR if you'd like to add others.
